#!/usr/bin/env node
// scripts/trs/from-export.js
// TRS Auto-Generator — reads l4-export and produces TRS markdown
// Owner: Node-01 (Architect) — M91 automation
//
// Usage:
//   node scripts/trs/from-export.js <l4-export.json> [--out docs/trs/]
//
// If --out is omitted, prints to stdout.
// If --out is a directory, auto-names: TRS-YYYYMMDD-XXX.md

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

function generateTRS(l4Export, opts = {}) {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
  const seq = opts.seq || '001';
  const id = `TRS-${dateStr}-${seq}`;

  // Extract fields from l4-export
  const alert = l4Export.alert || {};
  const channels = alert.channels || {};
  const push = channels.push || {};
  const vacuum = channels.vacuum || {};
  const patterns = push.patterns_detected || [];
  const level = alert.effective_level || 'unknown';
  const source = l4Export.meta?.source || 'unknown';
  const nodeId = l4Export.meta?.nodeId || 'unknown';
  const requestId = l4Export.request_id || crypto.randomUUID();

  // Build pattern summary
  const patternList = patterns.length > 0
    ? patterns.map(p => `- ${p.pattern || p.key || 'unknown'} (score: ${(p.score || 0).toFixed(3)})`).join('\n')
    : '- (no patterns detected)';

  // Build TRS markdown
  const md = `# ${id}

* **Generated:** ${now.toISOString()}
* **Source:** ${source}
* **Node ID:** ${nodeId} (hashed)
* **Request ID:** ${requestId}
* **Generator:** \`scripts/trs/from-export.js\` (auto)

---

## Result Summary

| Field | Value |
|-------|-------|
| Effective Level | ${level} |
| ACRI Score | ${(push.score || 0).toFixed(3)} |
| VRI Score | ${(vacuum.score || 0).toFixed(3)} |
| Pattern Count | ${patterns.length} |
| Confidence | ${push.confidence || 'N/A'} |

## Patterns Detected

${patternList}

## Flags

${(l4Export.flags || []).map(f => `- \`${f}\``).join('\n') || '- (none)'}

## Evidence Notes

${(l4Export.evidence || []).map((e, i) => `${i + 1}. ${e}`).join('\n') || '- (auto-generated — no evidence notes in export)'}

## Boundary Statement

> This is an automated observation record. It does not constitute diagnosis,
> judgment, or action recommendation. All outputs are auditable signals
> for human review. — SAFE mode

---

**Auto-generated by \`scripts/trs/from-export.js\`**
**Lumen ISSP — Information Sovereignty Shield Protocol** 🌙
`;

  return { id, md, dateStr };
}

// CLI entry
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.error('Usage: node scripts/trs/from-export.js <l4-export.json> [--out <dir>] [--seq 001]');
    process.exit(1);
  }

  const inputPath = args[0];
  const outIdx = args.indexOf('--out');
  const seqIdx = args.indexOf('--seq');
  const outDir = outIdx >= 0 ? args[outIdx + 1] : null;
  const seq = seqIdx >= 0 ? args[seqIdx + 1] : '001';

  const raw = fs.readFileSync(inputPath, 'utf-8');
  const l4Export = JSON.parse(raw);
  const { id, md } = generateTRS(l4Export, { seq });

  if (outDir) {
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${id}.md`);
    fs.writeFileSync(outPath, md, 'utf-8');
    console.log(`✅ Written: ${outPath}`);
  } else {
    process.stdout.write(md);
  }
}

module.exports = { generateTRS };
